export const cdsw_frequery = [
  // Clean up #"frequency": ".*",
  // #L0
  {
    testset: "cdsw:mlx_nightly",
    releases: ["mlx-wl-app-2.0", "mlx-wl-app-2.0.9"],
    frequency: "none",
    owner_id: "cdswtest-notify",
  },
  {
    testset: "cdsw:cml_pvc_ocp_gpu_tests",
    releases: ["mlx-wl-app-2.0"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_ocp_gpu_tests_150",
    releases: ["private_cloud_1.5.0"],
    frequency: "0 6 * * 7",
    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_multi_region_certification_suite_dev",
    releases: ["mlx-wl-app-2.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:amps_nightly",
    releases: ["mlx-cp-app-1.x"],
    frequency: "0 10 * * 1,4",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:mlx_wl_weekly_tests",
    releases: ["mlx-cp-app-1.x"],
    frequency: "0 6 * * 7",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:cml_pvc_amps_tests",
    releases: ["private_cloud_1.5.0"],
    frequency: "0 10 * * 1,4",

    preconditions: ["L0_PASSED"],
    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:mlx_mow_dev_nightly_cluster",
    releases: ["mlx-wl-app-2.0"],
    frequency: "0 3 * * 1-5",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:mlx_model_registry_nightly",
    releases: ["mlx-wl-app-2.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:mlx_mow_dev_model_registry_nightly",
    releases: ["mlx-wl-app-2.0"],
    frequency: "0 22 * * 0-4",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:mlx_mow_int_model_registry_nightly",
    releases: ["mlx-wl-app-2.0"],
    frequency: "0 22 * * 1-5",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:mlx_mow_int_nightly_cluster",
    releases: ["mlx-wl-app-2.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:cml_mlops_e2e_nightly",
    releases: ["mlx-wl-app-2.0"],
    frequency: "0 22 * * 1-5",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:cml_pvc_e2e_upgrades",
    releases: ["private_cloud_1.3.4"],

    frequency: "none",
    preconditions: [],
    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_e2e_upgrades_134",
    releases: ["private_cloud_1.3.4"],

    frequency: "none",
    preconditions: [],
    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_ecs_functional_tests",
    releases: ["private_cloud_1.5.4"],
    frequency: "0 9 * * 1,4",

    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_functional_tests_ocp_minimal",
    releases: ["private_cloud_1.5.1"],
    frequency: "0 9 * * 1-5",

    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_ocp_functional_tests",
    releases: ["mlx-cp-app-1.32"],

    frequency: "none",
    quanta_tags: ["tier=L2"],
    allow_reruns_on_same_composites: false,
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:REFRESH_MASTER_NIGHTLY_CLUSTER",
    releases: ["cdsw2.0.0-cdh6.3.4"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW20x_NIGHTLY_CLUSTER",
    releases: ["cdsw2.0.0-cdh7.1.7.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW1105_NIGHTLY_CLUSTER",
    releases: ["cdsw1.10.5-cdh7.1.9-cm7.11.3"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW110x_NIGHTLY_CLUSTER",
    releases: ["cdsw1.10.4-cdh7.1.7.1000"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW19x_NIGHTLY_CLUSTER",
    releases: ["cdsw1.9.2-cdh7.1.7.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW18x_NIGHTLY_CLUSTER",
    releases: ["cdsw1.8.0-cdh7.1.1.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW17x_NIGHTLY_CLUSTER",
    releases: ["cdsw1.7.2-cdh6.3.4"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW16x_NIGHTLY_CLUSTER",
    releases: ["cdsw1.6.1-cdh6.2.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW15x_NIGHTLY_CLUSTER",
    releases: ["cdsw1.5.0-cdh5.16.0"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW130_NIGHTLY_CLUSTER",
    releases: ["cdsw1.3.1-cdh5.14.4-spark2.2"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:REFRESH_CDSW140_NIGHTLY_CLUSTER",
    releases: ["cdsw1.4.3-cdh5.15.2"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:ENDURANCE_TESTSET",
    releases: ["cdsw1.10.0-cdh7.1.7.0"],

    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:ENDURANCE_CLUSTER_CHECKING",
    releases: ["cdsw1.8.0-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:cdsw20x_c7_nightly",
    releases: ["cdsw2.0.0-cdh7.1.7.0"],
    frequency: "0 17 * * 0-4",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw20x_c6_nightly",
    releases: ["cdsw2.0.0-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw110_c7_nightly",
    releases: ["cdsw1.10.4-cdh7.1.7.1000"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw110_c6_nightly",
    releases: ["cdsw1.10.4-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw19_c7_nightly",
    releases: ["cdsw1.9.2-cdh7.1.7.0"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw19_c6_nightly",
    releases: ["cdsw1.9.2-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw19_c5_nightly",
    releases: ["cdsw1.9.2-cdh5.17.0"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw18_c7_nightly",
    releases: ["cdsw1.8.0-cdh7.1.1.0"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw18_c6_nightly",
    releases: ["cdsw1.8.0-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw18_c5_nightly",
    releases: ["cdsw1.8.0-cdh5.17.0"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw15x_c6_nightly",
    releases: ["cdsw1.5.0-cdh6.1.0"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw15x_c5_nightly",
    releases: ["cdsw1.5.0-cdh5.16.0"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw172_c6_nightly",
    releases: ["cdsw1.7.2-cdh6.3.4"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw_l0",
    releases: ["cdsw2.0.0-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw20x_c7_weekly",
    releases: ["cdsw2.0.0-cdh7.1.7.0"],
    frequency: "0 5 * * 2",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw20x_c6_weekly",
    releases: ["cdsw2.0.0-cdh6.3.4"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw20x_weekly_gpu",
    releases: ["cdsw2.0.0-cdh7.1.7.0"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw110_c7_weekly",
    releases: ["cdsw1.10.4-cdh7.1.7.1000"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw110_c6_weekly",
    releases: ["cdsw1.10.4-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw19_c7_weekly",
    releases: ["cdsw1.9.2-cdh7.1.7.0"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw19_c6_weekly",
    releases: ["cdsw1.9.2-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw18_c7_weekly",
    releases: ["cdsw1.8.0-cdh7.1.1.0"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw18_c6_weekly",
    releases: ["cdsw1.8.0-cdh6.3.4"],
    frequency: "none",

    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw172_c6_weekly",
    releases: ["cdsw1.7.2-cdh6.3.4"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw15x_c6_weekly",
    releases: ["cdsw1.5.0-cdh6.1.0"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw15x_c5_weekly",
    releases: ["cdsw1.5.0-cdh5.16.0"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw20x_c6_scale_weekly",
    releases: ["cdsw2.0.0-cdh6.3.4"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw14x_c5_nightly",
    releases: ["cdsw1.4.3-cdh5.15.1"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw14x_c5_weekly",
    releases: ["cdsw1.4.3-cdh5.15.1"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw_weekly_c5",
    releases: ["cdsw1.4.2-cdh5.15.1"],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw131_redhat75_qualification",
    releases: ["cdsw1.3.1-cdh5.14.4-spark2.2"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:cdsw_nightly_c5",
    releases: ["cdsw1.4.2-cdh5.15.1"],
    frequency: "none",
    owner_id: "cdswtest",
  },
  {
    testset: "cdsw:cml_runtime_systests",
    releases: ["mlx-wl-app-2.0.45"],
    frequency: "0 17 * * 3",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw_runtime_systests",
    releases: ["cdsw1.10.4-cdh7.1.7.1000-runtime9999.12"],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_to_2x",
    releases: [
      "cdsw1.10.4-cdh6.3.4",
      "cdsw1.10.3-cdh6.3.4",
      "cdsw1.10.2-cdh6.3.4",
      "cdsw1.10.1-cdh6.3.4",
      "cdsw1.10.0-cdh6.3.4",
      "cdsw1.9.2-cdh6.3.4",
      "cdsw1.9.1-cdh6.3.4",
      "cdsw1.9.0-cdh6.3.4",
    ],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_to_1104",
    releases: [
      "cdsw1.10.3-cdh6.3.4",
      "cdsw1.10.2-cdh6.3.4",
      "cdsw1.10.1-cdh6.3.4",
      "cdsw1.10.0-cdh6.3.4",
      "cdsw1.9.2-cdh6.3.4",
      "cdsw1.9.1-cdh6.3.4",
      "cdsw1.9.0-cdh6.3.4",
      "cdsw1.8.1-cdh6.3.4",
      "cdsw1.8.0-cdh6.3.4",
    ],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_to_192",
    releases: [
      "cdsw1.9.1-cdh6.3.4",
      "cdsw1.9.0-cdh6.3.4",
      "cdsw1.8.1-cdh6.3.4",
      "cdsw1.8.0-cdh6.3.4",
      "cdsw1.7.2-cdh6.3.4",
      "cdsw1.7.1-cdh6.3.4",
    ],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_to_180",
    releases: [
      "cdsw1.7.2-cdh6.3.4",
      "cdsw1.7.1-cdh6.3.4",
      "cdsw1.6.1-cdh6.2.0",
      "cdsw1.6.0-cdh6.1.0",
    ],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_to_172",
    releases: [
      "cdsw1.6.1-cdh6.2.0",
      "cdsw1.6.0-cdh6.1.0",
      "cdsw1.5.0-cdh6.1.0",
    ],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["spot", "on_demand"],
  },
  {
    testset: "cdsw:cml_pvc_lapost_base_cluster_refresh",
    releases: ["mlx-cp-app-1.x"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_base_cluster_refresh",
    releases: ["mlx-cp-app-1.x"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_ecs_base_cluster_ycloud_refresh",
    releases: ["mig-cdsw1.10.5-pvc1.5.2"],
    frequency: "0 0 * * 0",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_ecs_base_cluster_ycloud_refresh_mig",
    releases: ["mig-cdsw1.10.0-pvc1.5.1"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cml_pvc_ecs_l2_base_cluster_ycloud_refresh",
    releases: ["private_cloud_1.5.1"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:nightly_cml_pvc_env_refresh",
    releases: ["private_cloud_1.5.0"],
    frequency: "0 3 * * 1-5",

    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:nightly_ocp_pvc_base_cluster_refresh",
    releases: ["mlx-cp-app-1.x"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_openstack_to_2x",
    releases: ["cdsw1.10.4-cdh6.3.4", "cdsw1.9.2-cdh6.3.4"],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_openstack_to_1104",
    releases: [
      "cdsw1.10.3-cdh6.3.4",
      "cdsw1.10.2-cdh6.3.4",
      "cdsw1.10.1-cdh6.3.4",
      "cdsw1.10.0-cdh6.3.4",
      "cdsw1.9.2-cdh6.3.4",
      "cdsw1.9.1-cdh6.3.4",
      "cdsw1.9.0-cdh6.3.4",
      "cdsw1.8.1-cdh6.3.4",
      "cdsw1.8.0-cdh6.3.4",
    ],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_openstack_to_192",
    releases: [
      "cdsw1.9.1-cdh6.3.4",
      "cdsw1.9.0-cdh6.3.4",
      "cdsw1.8.1-cdh6.3.4",
      "cdsw1.8.0-cdh6.3.4",
      "cdsw1.7.2-cdh6.3.4",
      "cdsw1.7.1-cdh6.3.4",
    ],

    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_openstack_to_180",
    releases: [
      "cdsw1.7.2-cdh6.3.4",
      "cdsw1.7.1-cdh6.3.4",
      "cdsw1.6.1-cdh6.2.0",
      "cdsw1.6.0-cdh6.1.0",
    ],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cdsw1x_c6_upgrade_openstack_to_172",
    releases: [
      "cdsw1.6.1-cdh6.2.0",
      "cdsw1.6.0-cdh6.1.0",
      "cdsw1.5.0-cdh6.1.0",
    ],
    frequency: "none",
    owner_id: "cdswtest",
    retry: ["on_demand"],
  },
  {
    testset: "cdsw:cml_platform_single_node_certification",
    releases: ["private_cloud_1.5.1"],
    frequency: "0 3 * * 1",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ecs_and_cm_and_cml_only_pre_post_upgrade_public",
    releases: ["private_cloud_1.5.1"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ecs_and_cm_and_cml_only_pre_post_upgrade_embedded",
    releases: ["private_cloud_1.5.1"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ecs_and_cm_and_cml_only_pre_post_upgrade_public_141",
    releases: ["private_cloud_1.5.1"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ecs_and_cm_and_cml_only_pre_post_upgrade_embedded_141",
    releases: ["private_cloud_1.5.1"],

    frequency: "none",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ecs_amp_tests_pvc_151_kcloud",
    releases: ["private_cloud_1.5.1"],
    frequency: "0 6 * * 2",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ecs_gpu_tests_pvc_151_kcloud",
    releases: ["private_cloud_1.5.1"],
    frequency: "0 6 * * 3",
    owner_id: "cml_pvc_testing",
  },
  {
    testset: "cdsw:ocp_gpu_tests_pvc_151",
    releases: ["private_cloud_1.5.1"],
    frequency: "0 6 * * 3",
    owner_id: "cml_pvc_testing",
  },
];

export const e2e_freq = [
  {
    testset: "E2E:private_cloud_e2e_test_L0_Ldap",
    frequency: "none",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.2"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:E2E_ECS_kcloud_OCP",
    frequency: "none",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.3.4"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:E2E_ECS_existingcm_kcloud_OCP",
    frequency: "L0",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:E2E_ECS_existingcm_kcloud_OCP_cm71130_pvc150",
    frequency: "0 0 * * 1-5",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.5.0_cm7.11.3.0_cdh7.1.8"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:E2E_ECS_existingcm_kcloud_OCP_cm71130_pvc151",
    frequency: "0 12 * * 1-5",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.5.1_cm7.11.3.0_cdh7.1.8"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:E2E_ECS_existingcm_kcloud_OCP_on_master",
    frequency: "0 6,18 * * *",
    owner_id: "e2e_runs",
    releases: ["private_cloud_2.0.0"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:interop_pvc_base_cluster_refresh",
    releases: ["private_cloud_1.0"],
    frequency: "none",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:nightly_pvc_base_cluster_refresh",
    releases: ["private_cloud_1.0"],
    frequency: "0 0 8 * *",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:ECS_base_cluster_refresh",
    releases: ["private_cloud_1.3.3-h1"],
    frequency: "none",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:Kcloud_base_cluster_refresh",
    releases: ["private_cloud_1.5.4"],
    frequency: "0 9 * * 3,6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:Kcloud_base_cluster_refresh_on_master_branch",
    releases: ["private_cloud_2.0.0"],
    frequency: "0 3 * * 3,6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:interop_pvc_base_cluster_refresh_postgress",
    releases: ["private_cloud_1.5.4"],
    frequency: "0 9 * * 3,6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:interop_pvc_base_cluster_refresh_postgress_on_master_branch",
    releases: ["private_cloud_2.0.0"],
    frequency: "0 3 * * 3,6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:Kcloud_base_cluster_refresh_rm_target",
    releases: ["private_cloud_1.5.1"],
    frequency: "0 9 * * 3,6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:Kcloud_nightly_base_cluster_refresh",
    releases: ["private_cloud_1.4.0"],
    frequency: "0 0 * * 6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:interop_pvc_base_cluster_cleanup",
    releases: ["private_cloud_1.3.4"],
    frequency: "0 13 * * *",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:interop_pvc_base_cluster_refresh_postgress_canary",
    releases: ["private_cloud_1.5.4"],
    frequency: "0 0 * * 6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:interop_pvc_base_cluster_refresh_postgress_canary_717",
    releases: ["private_cloud_1.5.3"],
    frequency: "0 0 * * 6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:interop_pvc_base_cluster_refresh_postgress_canary_718",
    releases: ["private_cloud_1.5.3"],
    frequency: "0 0 * * 6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:Kcloud_canary_base_cluster_refresh",
    releases: ["private_cloud_1.5.3"],
    frequency: "0 0 * * 6",
    owner_id: "e2e_runs",
  },
  {
    testset: "E2E:private_cloud_e2e_test_nightly_1cm1dc_split1",
    frequency: "0 0 * * *",
    preconditions: ["L0_PASSED"],
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.2"],
    quanta_tags: ["E2E"],
  },
  {
    testset: "E2E:private_cloud_e2e_test_nightly_1cm1dc_split2",
    frequency: "0 1 * * *",
    preconditions: ["L0_PASSED"],
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.2"],
    quanta_tags: ["E2E"],
  },
  {
    testset: "E2E:E2E_ecs_old_cm_kcloud_nightly_test",
    frequency: "0 1 * * *",
    preconditions: ["L0_PASSED"],
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.4.0"],
    quanta_tags: ["E2E"],
  },
  {
    testset: "E2E:private_cloud_e2e_test_nightly_split1",
    frequency: "none",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.0"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:private_cloud_e2e_test_nightly_split2",
    frequency: "none",
    owner_id: "e2e_runs",
    releases: ["private_cloud_1.0"],
    quanta_tags: ["E2E", "private-cloud-ga", "private-cloud-L0"],
  },
  {
    testset: "E2E:ts_upgrade_with_e2e_tests153to154",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_upgrade_with_e2e_tests152to154",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_cm_and_ecs_upgrade_with_e2e_151",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.3"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_cm_and_ecs_upgrade_with_e2e_152",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_cm_and_ecs_upgrade_with_e2e_153",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_preupgrade_base_refresh153to154",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_preupgrade_base_refresh152to154",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.4"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_150_preupgrade",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.1"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_141_preupgrade",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.1"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_upgrade_with_e2e_new_cm_tests1",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.1"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
  {
    testset: "E2E:ts_upgrade_with_e2e_new_cm_tests2",
    frequency: "none",
    owner_id: "upgrade_with_e2e",
    releases: ["private_cloud_1.5.1"],
    quanta_tags: ["E2E", "upgrade", "tier=L2"],
  },
];
